name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '11', '17', '22' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - uses: gradle/actions/setup-gradle@v4
      - name: Lint Java code
        run: gradle spotlessJavaCheck
      - name: Test Java code
        run: gradle test
